#!/usr/bin/env bash

set -e

USAGE="Usage: final_release VERSION 'Description of the release'"

if [[ $# -ne 2 ]]; then
  echo "Illegal number of parameters"
  echo $USAGE
  exit
fi


RELEASE_NAME=nfs
RELEASE_DIR=~/workspace/$RELEASE_NAME-boshrelease
VERSION=$1


echo "Creates bosh final release"
if [ ! -f releases/nfs/nfs-$VERSION ]; then
  bosh create release --final --version $VERSION --force 
  git ci
fi

git push origin master

echo "Creating git tag v$VERSION"
git tag v$VERSION

echo "Push git tag v$VERSION"
git push --tags

