#!/bin/sh
# vim: set ft=sh

set -e 
set -x

if [ -n "$token" ]; then
  wget_args="--post-data='' --header='Authorization: Token $token'"
fi

if [ -z "$dest" ]; then
  curl -k -O $url
else 
  eval "wget -O $dest --no-check-certificate $wget_args $url"
fi
