#!/bin/bash

set -e

infrastructure=$1

if [ "$infrastructure" != "aws-ec2" ] && \
    [ "$infrastructure" != "vsphere" ] && \
    [ "$infrastructure" != "warden" ] ; then
  echo "usage: ./make_manifest <aws-ec2|warden|vsphere>"
  exit 1
fi

shift

templates=~/workspace/nfs-boshrelease/templates

spiff merge \
  $templates/deployment.yml \
  $templates/jobs.yml \
  $templates/infrastructure-${infrastructure}.yml \
  $* 

